import "./src/styles/index.css"
import "./src/styles/layout.scss"
import "./src/styles/header.scss"
import "./src/styles/body.scss"
import "./src/styles/generics.scss"
import "./src/styles/responsive.scss"
import "./src/styles/premade/animated-hover.css"
